#!/usr/bin/ruby

## Even Fibonacci numbers
#
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

m = 4000000

fib = Enumerator.new do |y|
  prev = 0
  curr = 1
  loop do
    y.yield curr
    prev, curr = [curr, curr + prev]
  end
end

puts fib.take_while { |n| n < m }.select(&:even?).inject(0, :+)

